name: Test CLI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  template:
    name: Test template
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test script
        run: |
          ./.template.py -a

  gitscan:
    name: Test gitscan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test script
        run: |
          ./gitscan.py -a ..

  duplexpdf:
    name: Test duplexpdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test script
        run: |
          pip install PyPDF2
          ./duplexpdf.py tests/duplexpdf.pdf